apiVersion: v1
kind: Service
metadata:
  name: microkafka
  labels:
    app: microkafka
spec:
  selector:
    app: microkafka
  type: NodePort
  ports:
  - port: 2181
    targetPort: 2181
    name: zk
  - port: 9092
    targetPort: 9092
    name: kafka
